# Generated by Django 5.2.12 on 2026-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_admin_approve', 'Waiting Admin Approve'), ('waiting_user_received', 'Waiting User Received Item'), ('finished', 'Finished'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
