# Generated by Django 5.2.12 on 2026-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
