# Generated by Django 5.2.12 on 2026-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_active_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
