# Generated by Django 5.2.12 on 2026-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
